# Generated by Django 3.2.12 on 2022-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0017_alter_grade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Degree', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
