# Generated by Django 3.2.12 on 2022-10-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0018_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categorie',
        ),
        migrations.AddField(
            model_name='licences',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.categorie'),
        ),
        migrations.AddField(
            model_name='licences',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.degree'),
        ),
        migrations.AddField(
            model_name='licences',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.grade'),
        ),
        migrations.AddField(
            model_name='licences',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.weights'),
        ),
    ]
