# Generated by Django 3.2.12 on 2022-10-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0019_auto_20221021_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='licences',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.club'),
        ),
        migrations.AddField(
            model_name='licences',
            name='state',
            field=models.TextField(default='En Attente'),
        ),
        migrations.AddField(
            model_name='licences',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
