# Generated by Django 3.2.12 on 2022-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0022_auto_20221021_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licences',
            name='id',
        ),
        migrations.AlterField(
            model_name='licences',
            name='num_licences',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
