# Generated by Django 3.2.12 on 2022-11-03 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalback', '0023_auto_20221021_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licences',
            options={},
        ),
        migrations.AlterField(
            model_name='licences',
            name='num_licences',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ArchivedLicences',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_licences', models.TextField(blank=True)),
                ('activated', models.BooleanField(default=False)),
                ('state', models.TextField(default='En Attente')),
                ('verified', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.categorie')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.club')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.degree')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.discipline')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.grade')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.role')),
                ('seasons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.seasons')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.weights')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
