# Generated by Django 3.2.12 on 2022-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0025_bracket_competition_match_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='arbitrators',
            field=models.ManyToManyField(to='finalback.Arbitrator'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(to='finalback.Athlete'),
        ),
    ]
