# Generated by Django 3.2.12 on 2022-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0026_auto_20221129_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='arbitrators',
            field=models.ManyToManyField(blank=True, null=True, to='finalback.Arbitrator'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='finalback.Athlete'),
        ),
    ]
