# Generated by Django 3.2.12 on 2022-12-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0027_auto_20221129_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.categorie'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.discipline'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='ligue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.ligue'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.seasons'),
        ),
    ]
