# Generated by Django 3.2.12 on 2022-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0029_competition_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='attendents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
