# Generated by Django 3.2.12 on 2022-12-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0031_auto_20221209_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='idantity_photo',
            new_name='identity_photo',
        ),
    ]
