# Generated by Django 3.2.12 on 2022-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0032_rename_idantity_photo_athlete_identity_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/discipline/'),
        ),
    ]
