# Generated by Django 3.2.12 on 2022-12-13 09:15

from django.db import migrations, models
import finalback.common


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0034_club_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=finalback.common.get_upload_path)),
                ('path', models.TextField(blank=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('extension', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='identity_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='medical_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
