# Generated by Django 3.2.12 on 2022-12-13 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalback', '0036_auto_20221213_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='season',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.seasons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
    ]
