# Generated by Django 3.2.12 on 2022-12-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0038_alter_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='sex',
        ),
    ]
