# Generated by Django 3.2.12 on 2022-12-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0039_auto_20221213_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitrator',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='arbitrator',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='arbitrator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='arbitrator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='arbitrator',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='sex',
        ),
        migrations.AddField(
            model_name='arbitrator',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arbitrator',
            name='identity_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbitrator',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='degree_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='grade_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='identity_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
