# Generated by Django 3.2.12 on 2022-12-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0041_coach_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='cin',
        ),
    ]
