# Generated by Django 3.2.12 on 2022-12-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0045_alter_coach_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrator',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supporter',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.club'),
            preserve_default=False,
        ),
    ]
