# Generated by Django 3.2.12 on 2022-12-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0047_auto_20221222_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.categorie'),
            preserve_default=False,
        ),
    ]
