# Generated by Django 3.2.12 on 2022-12-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0048_coach_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='weights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.weights'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.categorie'),
        ),
    ]
