# Generated by Django 3.2.12 on 2023-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0049_auto_20221222_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
