# Generated by Django 3.2.12 on 2023-02-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0050_profile_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.competition'),
            preserve_default=False,
        ),
    ]
