# Generated by Django 3.2.12 on 2023-02-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0053_auto_20230203_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.bracket'),
        ),
    ]
