# Generated by Django 3.2.12 on 2023-02-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0054_alter_match_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='arbitrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.arbitrator'),
        ),
        migrations.AlterField(
            model_name='match',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_final',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant1', to='finalback.athlete'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant2', to='finalback.athlete'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.TextField(blank=True, default='En Attente', null=True),
        ),
    ]
