# Generated by Django 3.2.12 on 2023-02-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0055_auto_20230203_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.discipline'),
            preserve_default=False,
        ),
    ]
