# Generated by Django 3.2.12 on 2023-02-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0056_athlete_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitrator',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.grade'),
        ),
    ]
