# Generated by Django 3.2.12 on 2023-03-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0061_alter_coach_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.discipline'),
            preserve_default=False,
        ),
    ]
